# Generated by Django 4.2.4 on 2024-08-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsB', '0005_checklistb_created_at_checklistb_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistb',
            name='contractor_zip_code',
            field=models.CharField(max_length=23, verbose_name='Contractor Zip Code'),
        ),
        migrations.AlterField(
            model_name='checklistb',
            name='work_zip_code',
            field=models.CharField(max_length=23, verbose_name='Work Zip Code'),
        ),
    ]
