# Generated by Django 4.2.4 on 2024-07-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsD', '0005_alter_checklistd_contractor_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformer',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='impedance',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='type',
        ),
    ]
