# Generated by Django 4.2.4 on 2024-11-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsD', '0009_checklistd_contractor_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistd',
            name='concessionaire',
            field=models.CharField(blank=True, choices=[('ENEL-SP', 'ENEL-SP')], max_length=20, null=True),
        ),
    ]
