# Generated by Django 4.2.4 on 2024-03-18 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('GIR', 'GIR'), ('Group', 'Group')], default='Gimi', max_length=5, verbose_name='Company')),
                ('budget_number', models.CharField(max_length=10, verbose_name='Budget Number')),
                ('client_name', models.CharField(max_length=120, verbose_name='Client Name')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Cliente Email')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.checklist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.product')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='products',
            field=models.ManyToManyField(through='checklists.ChecklistProduct', to='checklists.product'),
        ),
    ]
