# Generated by Django 4.2.4 on 2024-05-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_checklist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='answered_registration',
            field=models.BooleanField(default=False, verbose_name='Answered Registration'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, through='checklists.ChecklistProduct', to='checklists.product'),
        ),
    ]
