# Generated by Django 4.2.4 on 2024-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_checklist_answered_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistproduct',
            name='items_answered',
        ),
        migrations.RemoveField(
            model_name='checklistproduct',
            name='items_numbers',
        ),
        migrations.RemoveField(
            model_name='checklistproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='checklistproduct',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Answered'),
        ),
        migrations.AddField(
            model_name='checklistproduct',
            name='item',
            field=models.CharField(default='1', max_length=3, verbose_name='Item'),
        ),
    ]
