# Generated by Django 4.2.4 on 2024-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_remove_checklistproduct_items_answered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='answered_optional',
            field=models.BooleanField(default=False, verbose_name='Answered Optional'),
        ),
    ]
