# Generated by Django 4.2.4 on 2024-07-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_checklist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='answered_art',
            field=models.BooleanField(default=False, verbose_name='Answered ART'),
        ),
    ]
