# Generated by Django 4.2.4 on 2024-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0011_checklist_answered_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='answered_art',
        ),
        migrations.AddField(
            model_name='checklist',
            name='art_status',
            field=models.IntegerField(choices=[(1, 'NOT SENT'), (2, 'SENT'), (3, 'ANSWERED')], default=1),
        ),
    ]
