# Generated by Django 4.2.4 on 2025-02-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0013_remove_checklist_answered_optional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='auxiliary_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Auxiliary Number'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='construction_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Construction Name'),
        ),
    ]