# Generated by Django 4.2.4 on 2024-04-30 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0006_checklist_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('process_number', models.CharField(max_length=10, verbose_name='Process Number')),
                ('company', models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('GIR', 'GIR')], default='Gimi', max_length=4, verbose_name='Company')),
                ('concessionaire', models.CharField(blank=True, choices=[('CEEE', 'CEEE'), ('CELESC', 'CELESC'), ('CEMIG', 'CEMIG'), ('CERIPA', 'CERIPA'), ('COELBA', 'COELBA'), ('CPFL', 'CPFL'), ('EDP_SP', 'EDP-SP'), ('EDP_ES', 'EDP-ES'), ('ELEKTRO', 'ELEKTRO'), ('ENEL', 'ENEL'), ('ENERGISA', 'ENERGISA'), ('EQUATORIAL', 'EQUATORIAL'), ('LIGHT', 'LIGHT')], default='CEEE', max_length=20, null=True)),
                ('other_concessionaire', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_voltage', models.FloatField(verbose_name='Primary Voltage (kV)')),
                ('panel_usage', models.CharField(choices=[('Sheltered', 'Sheltered'), ('Unsheltered', 'Unsheltered')], default='Sheltered', max_length=20, verbose_name='Panel Usage')),
                ('cable_side', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=20, verbose_name='Panel Usage')),
                ('contracted_demand', models.CharField(max_length=8, verbose_name='Contracted Demand')),
                ('fire_exit', models.BooleanField(blank=True, default=False, null=True, verbose_name='Transformer Fire Exit')),
                ('fire_transformer_power', models.FloatField(blank=True, null=True, verbose_name='Fire Transformer Power')),
                ('measurements_consumers_quantity', models.PositiveIntegerField(verbose_name='Measurements/Consumers')),
                ('contractor_name', models.CharField(max_length=50, verbose_name='Contractor Name')),
                ('contractor_document', models.CharField(max_length=18, verbose_name='Contractor Document')),
                ('contractor_contact', models.CharField(max_length=50, verbose_name='Contractor Contact')),
                ('contractor_phone', models.CharField(max_length=13, verbose_name='Contractor Phone')),
                ('contractor_street', models.CharField(max_length=255, verbose_name='Contractor Street')),
                ('contractor_number', models.CharField(max_length=20, verbose_name='Contractor Number')),
                ('contractor_complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contractor Complement')),
                ('contractor_neighborhood', models.CharField(max_length=100, verbose_name='Contractor Neighborhood')),
                ('contractor_city', models.CharField(max_length=100, verbose_name='Contractor City')),
                ('contractor_state', models.CharField(max_length=50, verbose_name='Contractor State')),
                ('contractor_zip_code', models.CharField(max_length=20, verbose_name='Contractor Zip Code')),
                ('owner_name', models.CharField(max_length=50, verbose_name='Owner Name')),
                ('owner_document', models.CharField(max_length=18, verbose_name='Owner Document')),
                ('owner_contact', models.CharField(max_length=50, verbose_name='Owner Contact')),
                ('owner_phone', models.CharField(max_length=13, verbose_name='Owner Phone')),
                ('work_street', models.CharField(max_length=255, verbose_name='Work Street')),
                ('work_number', models.CharField(max_length=20, verbose_name='Work Number')),
                ('work_complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Work Complement')),
                ('work_neighborhood', models.CharField(max_length=100, verbose_name='Work Neighborhood')),
                ('work_city', models.CharField(max_length=100, verbose_name='Work City')),
                ('work_state', models.CharField(max_length=50, verbose_name='Work State')),
                ('work_zip_code', models.CharField(max_length=20, verbose_name='Work Zip Code')),
                ('gimi_study', models.BooleanField(default=False, verbose_name='Gimi Study?')),
                ('icc3f', models.FloatField(blank=True, null=True, verbose_name='Icc3f')),
                ('icc2f', models.FloatField(blank=True, null=True, verbose_name='Icc2f')),
                ('iccftmax', models.FloatField(blank=True, null=True, verbose_name='Icc3f')),
                ('iccftmin', models.FloatField(blank=True, null=True, verbose_name='Icc3f')),
                ('have_study', models.BooleanField(default=False, verbose_name='Have Study?')),
                ('study_prediction', models.DateField(verbose_name='Study Prediction')),
                ('breakers_quantity', models.PositiveIntegerField(verbose_name='Breakers Quantity')),
                ('parent_checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklists.checklist', verbose_name='Parent Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveIntegerField(verbose_name='Transformer Power')),
                ('impedance', models.FloatField(blank=True, null=True, verbose_name='Impedance')),
                ('demand', models.FloatField(blank=True, null=True, verbose_name='Demand')),
                ('type', models.CharField(blank=True, choices=[('Air', 'Air'), ('Oil', 'Oil')], max_length=3, null=True, verbose_name='Type')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='checklistsC.checklistc')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentTransformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.CharField(max_length=10, verbose_name='CT Ratio')),
                ('accuracy', models.CharField(max_length=30, verbose_name='CT Accuracy')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_transformers', to='checklistsC.checklistc')),
            ],
        ),
    ]
