# Generated by Django 4.2.4 on 2024-05-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsC', '0002_alter_checklistc_study_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformer',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='impedance',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='type',
        ),
    ]
