# Generated by Django 4.2.4 on 2024-06-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsC', '0006_checklistc_fire_transformer_demand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistc',
            name='item',
            field=models.CharField(default='1', max_length=3, verbose_name='Item'),
        ),
    ]
