# Generated by Django 4.2.4 on 2024-07-20 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsC', '0009_alter_checklistc_concessionaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformer',
            name='checklist',
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformers_quantity', models.PositiveIntegerField(verbose_name='Transformers')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='checklistsC.checklistc')),
            ],
        ),
        migrations.AddField(
            model_name='transformer',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumersF', to='checklistsC.consumer'),
        ),
    ]
