# Generated by Django 4.2.4 on 2024-07-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsC', '0010_remove_transformer_checklist_consumer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumers', to='checklistsC.checklistc'),
        ),
    ]
