# Generated by Django 4.2.4 on 2024-07-20 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsC', '0011_alter_consumer_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformer',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='checklistsC.consumer'),
        ),
    ]
