# Generated by Django 4.2.4 on 2024-05-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformer',
            name='substation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='checklistsF.substation'),
        ),
    ]
