# Generated by Django 4.2.4 on 2024-07-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsF', '0005_checklistf_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistf',
            name='substations_quantity',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='substation',
        ),
        migrations.AddField(
            model_name='checklistf',
            name='cable_side',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=20, verbose_name='Cable Side'),
        ),
        migrations.AddField(
            model_name='checklistf',
            name='panel_usage',
            field=models.CharField(choices=[('Sheltered', 'Sheltered'), ('Unsheltered', 'Unsheltered')], default='Sheltered', max_length=20, verbose_name='Panel Usage'),
        ),
        migrations.AddField(
            model_name='checklistf',
            name='primary_voltage',
            field=models.FloatField(verbose_name='Primary Voltage (kV)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistf',
            name='transformers_quantity',
            field=models.PositiveIntegerField(verbose_name='Transformers Quantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transformer',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='checklistsF.checklistf'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Substation',
        ),
    ]
