# Generated by Django 4.2.4 on 2024-11-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsF', '0007_checklistf_created_at_checklistf_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistf',
            name='gimi_study',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gimi Study?'),
        ),
        migrations.AlterField(
            model_name='checklistf',
            name='have_study',
            field=models.BooleanField(blank=True, null=True, verbose_name='Have Study?'),
        ),
    ]
