# Generated by Django 4.2.4 on 2024-03-20 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('process_number', models.CharField(max_length=10, verbose_name='Process Number')),
                ('billing_cnpj', models.CharField(max_length=14, verbose_name='Billing CNPJ')),
                ('is_taxpayer', models.BooleanField(default=True, verbose_name='Is Taxpayer')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('minimum_value', models.FloatField(verbose_name='Minimum Value')),
                ('material_destination', models.CharField(choices=[('UC', 'Use and Consumption'), ('R', 'Resale'), ('I', 'Industrialization')], max_length=50, verbose_name='Material Destination')),
                ('nf_email', models.EmailField(max_length=254, verbose_name='NF Email')),
                ('additional_data', models.TextField(verbose_name='Additional Data')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('number', models.CharField(max_length=20, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complement')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Neighborhood')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('access_restriction', models.BooleanField(blank=True, null=True, verbose_name='Access Restriction')),
                ('payment_condition', models.CharField(max_length=120, verbose_name='Payment Condition')),
                ('down_payment_date', models.DateField(blank=True, null=True, verbose_name='Down Payment Date')),
                ('tr_name', models.CharField(max_length=50, verbose_name='TR Name')),
                ('tr_phone', models.CharField(max_length=13, verbose_name='TR Phone')),
                ('tr_email', models.EmailField(max_length=254, verbose_name='TR Email')),
                ('tr_name_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='TR Name')),
                ('tr_phone_2', models.CharField(blank=True, max_length=13, null=True, verbose_name='TR Phone')),
                ('tr_email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='TR Email')),
                ('mr_name', models.CharField(max_length=50, verbose_name='MR Name')),
                ('mr_phone', models.CharField(max_length=13, verbose_name='MR Phone')),
                ('mr_email', models.EmailField(max_length=254, verbose_name='MR Email')),
                ('mr_name_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='MR Name')),
                ('mr_phone_2', models.CharField(blank=True, max_length=13, null=True, verbose_name='MR Phone')),
                ('mr_email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='MR Email')),
                ('fr_name', models.CharField(max_length=50, verbose_name='FR Name')),
                ('fr_phone', models.CharField(max_length=13, verbose_name='FR Phone')),
                ('fr_email', models.EmailField(max_length=254, verbose_name='FR Email')),
                ('fr_name_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='FR Name')),
                ('fr_phone_2', models.CharField(blank=True, max_length=13, null=True, verbose_name='FR Phone')),
                ('fr_email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='FR Email')),
                ('commercial_satisfaction', models.CharField(max_length=1, verbose_name='Commercial Satisfaction')),
                ('budget_satisfaction', models.CharField(max_length=1, verbose_name='Budget Satisfaction')),
                ('suggestions', models.TextField(verbose_name='Suggestions')),
            ],
        ),
    ]
