# Generated by Django 4.2.4 on 2024-03-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='access_restriction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Access Restriction'),
        ),
    ]
