# Generated by Django 4.2.4 on 2024-03-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_registration_access_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='additional_data',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Data'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='suggestions',
            field=models.TextField(blank=True, null=True, verbose_name='Suggestions'),
        ),
    ]
