# Generated by Django 4.2.4 on 2024-03-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_alter_product_id'),
        ('registrations', '0004_alter_registration_budget_satisfaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='parent_checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklists.checklist', verbose_name='Parent Checklist'),
        ),
    ]
