# Generated by Django 4.2.4 on 2024-03-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_registration_parent_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='billing_cnpj',
            field=models.CharField(max_length=18, verbose_name='Billing CNPJ'),
        ),
    ]
