# Generated by Django 4.2.4 on 2024-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_alter_registration_billing_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='minimum_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Value'),
        ),
    ]
