# Generated by Django 4.2.4 on 2024-05-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_remove_registration_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='nf_email',
            field=models.TextField(verbose_name='NF Emails'),
        ),
    ]
