# Generated by Django 4.2.4 on 2024-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_alter_registration_nf_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fr_phone',
            field=models.CharField(max_length=15, verbose_name='FR Phone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fr_phone_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='FR Phone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='material_destination',
            field=models.CharField(choices=[('Uso e consumo', 'Uso e consumo'), ('Revenda', 'Revenda'), ('Industrialização', 'Industrialização')], max_length=50, verbose_name='Material Destination'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mr_phone',
            field=models.CharField(max_length=15, verbose_name='MR Phone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mr_phone_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='MR Phone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tr_phone',
            field=models.CharField(max_length=15, verbose_name='TR Phone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tr_phone_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TR Phone'),
        ),
    ]
