# Generated by Django 4.2.4 on 2024-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_alter_registration_fr_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='lr_document',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='registration',
            name='lr_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='LR Email'),
        ),
        migrations.AddField(
            model_name='registration',
            name='lr_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='registration',
            name='lr_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='LR Phone'),
        ),
    ]
