# Generated by Django 4.2.4 on 2024-07-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_registration_lr_document_registration_lr_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='lr_document',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='LR Document'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lr_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='LR Name'),
        ),
    ]
