# Generated by Django 4.2.4 on 2024-07-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_alter_registration_lr_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='deadline',
        ),
        migrations.AddField(
            model_name='registration',
            name='deadline_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Deadline'),
        ),
    ]
