# Generated by Django 4.2.4 on 2024-08-08 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_remove_registration_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='billing_cnpj',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='deadline_day',
        ),
        migrations.AddField(
            model_name='registration',
            name='billing_document',
            field=models.CharField(default=0, max_length=18, verbose_name='Billing Document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='billing_interval',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Billing Deadline'),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date'),
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
