# Generated by Django 4.2.4 on 2024-08-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_remove_registration_billing_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='zip_code',
            field=models.CharField(max_length=23, verbose_name='Zip Code'),
        ),
    ]
