# Generated by Django 4.2.4 on 2024-08-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_registration_latitude_registration_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='advance_billing_agreed',
            field=models.BooleanField(default=True, verbose_name='Advance Biliing Agreed?'),
        ),
    ]
