# Generated by Django 4.2.4 on 2024-12-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_registration_advance_billing_agreed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fr_name',
            field=models.CharField(max_length=70, verbose_name='FR Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fr_name_2',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='FR Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lr_name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='LR Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mr_name',
            field=models.CharField(max_length=70, verbose_name='MR Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mr_name_2',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='MR Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tr_name',
            field=models.CharField(max_length=70, verbose_name='TR Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tr_name_2',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='TR Name'),
        ),
    ]
