# Generated by Django 4.2.4 on 2024-07-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsG', '0003_alter_checklistg_contractor_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistg',
            name='item',
        ),
    ]
