# Generated by Django 4.2.4 on 2024-12-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsG', '0007_checklistg_contractor_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistg',
            name='contractor_contact',
            field=models.CharField(max_length=70, verbose_name='Contractor Contact'),
        ),
        migrations.AlterField(
            model_name='checklistg',
            name='contractor_name',
            field=models.CharField(max_length=70, verbose_name='Contractor Name'),
        ),
        migrations.AlterField(
            model_name='checklistg',
            name='owner_contact',
            field=models.CharField(max_length=70, verbose_name='Owner Contact'),
        ),
        migrations.AlterField(
            model_name='checklistg',
            name='owner_name',
            field=models.CharField(max_length=70, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='checklistg',
            name='responsible_name',
            field=models.CharField(max_length=70, verbose_name='Responsible Name'),
        ),
    ]
