# Generated by Django 4.2.4 on 2024-06-17 14:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0009_checklist_answered_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('process_number', models.CharField(max_length=10, verbose_name='Process Number')),
                ('company', models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GS', 'GS'), ('GIR', 'GIR')], default='Gimi', max_length=4, verbose_name='Company')),
                ('extended_warranty', models.BooleanField(verbose_name='Extended Warranty')),
                ('parent_checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklists.checklist', verbose_name='Parent Checklist')),
            ],
        ),
    ]
