# Generated by Django 4.2.4 on 2024-08-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionals', '0002_optional_created_at_optional_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optional',
            name='busbar_installation',
            field=models.BooleanField(default=False, verbose_name='Busbar Installation'),
        ),
        migrations.AddField(
            model_name='optional',
            name='coord_selectivity',
            field=models.BooleanField(default=False, verbose_name='Coord Selectivity'),
        ),
        migrations.AddField(
            model_name='optional',
            name='panel_commissioning',
            field=models.BooleanField(default=False, verbose_name='Panel Commissioning'),
        ),
        migrations.AddField(
            model_name='optional',
            name='protection_equipment',
            field=models.BooleanField(default=False, verbose_name='Protection Equipment'),
        ),
        migrations.AddField(
            model_name='optional',
            name='relay_commissioning',
            field=models.BooleanField(default=False, verbose_name='Relay Commissioning'),
        ),
        migrations.AddField(
            model_name='optional',
            name='relay_parameterization',
            field=models.BooleanField(default=False, verbose_name='Relay Parameterization'),
        ),
    ]
