# Generated by Django 4.2.4 on 2024-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsE', '0002_alter_checkliste_cable_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkliste',
            name='transformer_power',
            field=models.FloatField(verbose_name='Transformer Power'),
        ),
    ]
