# Generated by Django 4.2.4 on 2024-11-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistsE', '0008_checkliste_contractor_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkliste',
            name='concessionaire',
            field=models.CharField(blank=True, choices=[('ENEL', 'ENEL')], max_length=20, null=True),
        ),
    ]
